# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Sanjay
tagline:             'Technical Things'
description:         'Blog'
url:                 "https://sanjaykmenon.github.io"
#baseurl:             ""
paginate:            5

# About/contact
author:
  name:              Sanjay
  url:               https://twitter.com/sanjaykrishna
  email:             

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title:output_ext
# Google Analytics
google_analytics: UA-92287408-2


